---
kind: pipeline
type: kubernetes
name: build

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: docker
  commands:
  - docker build -t jetlify .
  volumes:
  - name: dockersock
    path: /var/run/

volumes:
- name: dockersock
  host:
    path: /var/run/

---
kind: signature
hmac: fb9af6d08226f8485823b04fc47c391103d7b14b6efe278f14d273fdd69f3d83

...
